#!/bin/bash

INDEX=" "
NAME="BROMACS"

if [[ $@ == *"-h"* ]]; then
echo "-f  : mdp file (req)"
echo "-p  : top file (req)"
echo "-c  : input coordinate file (req)"
echo "-oc : output coordinate file"
echo "-nt : #procs (req)"
echo "-nr : name of run"
echo "-n  : include to include index"
echo "-q  : node list"
echo "-qso: queso consideration"
echo "-detect to try to automatically find mdp, top, and gro"
exit 1
fi

commandline="$@"

commandline=$commandline" "

OGRO=confout.gro

node=''
queso='none'

#node="all.q@compute-0-0.local,all.q@compute-0-1.local,all.q@compute-0-10.local,all.q@compute-0-11.local,all.q@compute-0-12.local,all.q@compute-0-2.local,all.q@compute-0-3.local,all.q@compute-0-5.local,all.q@compute-0-6.local,all.q@compute-0-7.local,all.q@compute-0-8.local,all.q@compute-0-9.local"

if [ "${commandline/"-n "}" != "$commandline" ] ; then
INDEX="-n"
fi

while [[ $# > 1 ]];
do
key="$1"
case $key in
    -detect)
    GRO=`ls *.gro`
    if [ -e 'confout.gro' ] ; then
      GRO="confout.gro"
    fi
    TOP=`ls *.top`
    if [ -e 'mdout.mdp' ] ; then
      rm mdout.mdp
    fi
    MDP=`ls *.mdp`
    if [ -e 'confout.gro' ] ; then
      cp /home/scha0275/backups/nvt-run.mdp .
      MDP="nvt-run.mdp"
    fi
    shift
    ;;
    -q)
    node=$2
    shift
    ;;
    -f)
    MDP=$2
    shift
    ;;
    -p)
    TOP=$2
    shift
    ;;
    -c)
    GRO=$2
    shift
    ;;
    -nt)
    NUMPROC=$2
    shift
    ;;
    -nr)
    NAME=$2
    shift
    ;;
    -oc)
    OGRO=$2
    shift
    ;;
    -qso)
    queso="$2"
    shift
    ;;
esac
shift
done

if [ ${#MDP} -eq 0 ] || [ ${#TOP} -eq 0 ] || [ ${#GRO} -eq 0 ] ; then
echo -e "mdp: $MDP \ntop: $TOP \ngro: $GRO ;"
echo "bad info given, use -h for help"
exit 1
fi

JOBNAME="BROMACS"

if [ "$node" == '' ] ; then
  node=`/home/scha0275/program-workshop/python2.7/./queso.py "$queso" $NUMPROC`
fi

echo "gmx grompp -f $MDP -c $GRO -o Run.tpr -p $TOP $INDEX -v -maxwarn 2 >& Grompp.log " > cmd.file 
echo "gmx mdrun -nt $NUMPROC -s Run.tpr -c $OGRO" >> cmd.file

qsub <<  eof
#$ -S /bin/bash
#$ -q $node
#$ -N "$NAME"
#$ -l h_rt=999:00:00
#$ -pe mpi $NUMPROC 
#$ -cwd
#$ -j y
#$ -o Run.log 
#$ -a 1702191500

echo "BROMACS job running on the following processors:" > $JOBNAME.out
echo $PWD >> $JOBNAME.out
echo "grompp -f $mdp -c $gro -o Run.tpr -p $top $index -v >& Grompp.log" >> $JOBNAME.out
echo "mdrun -nt $NUMPROC -s Run.tpr" >> $JOBNAME.out
cat \$PE_HOSTFILE >> $JOBNAME.out

echo $PWD >> $JOBNAME.out

module load gromacs
export GMXLIB=/home/scha0275/gromacs/top/

export SCR=/scr/$USER/\$JOB_ID
mkdir \$SCR
export TMPDIR=\$SCR

echo "Starting GROMACS Job!" >> $JOBNAME.out

cp \$SGE_O_WORKDIR/* \$TMPDIR/

cd \$TMPDIR 

/home/scha0275/program-workshop/python2.7/./pynscheduling.py type=gmx procs=$NUMPROC starting jid=\$JOB_ID cmd=cmd.file

rm mdout.mdp

cp \$TMPDIR/* \$SGE_O_WORKDIR

/bin/rm -r \$SCR

echo "GROMACS Job Finished!" >> $JOBNAME.out

eof

echo "grompp -p $TOP -c $GRO -f $MDP -o Run.tpr $INDEX (logged to Grompp.log for troubleshooting)"
echo "mdrun -nt $NUMPROC -s Run.tpr -c $OGRO (logged to md.log for troubleshooting)"

