#!/bin/bash

proc=$1
name=$2
declare -a "top=(*.top)"
node=$3

if [ ${#top[@]} -gt 1 ]; then
    echo "more than one topology file found"
    exit 1
fi

if [ -e confout.gro ]; then
	gro="confout.gro"
	if [ ! -e "nvt-run.mdp" ]; then
	    cp /home/scha0275/backups/nvt-run.mdp .
	fi
	mdp="nvt-run.mdp"
else
	gro=*.gro
	mdp=*.mdp
fi

if [ -e "index.ndx" ]; then
	index="-n"
else
index=""
fi

echo "submitting to:" $node



JOBNAME="BROMACS"

if [[ $name == w-* ]] ; then
    cp /home/scha0275/backups/nvt-run.mdp .
    echo grompp -p $top -c $gro -f nvt-equil.mdp -o Run.tpr $index   "(logged to Grompp.log for troubleshooting)"
    echo mdrun -nt $proc -s Run.tpr                         "(logged to md.log for troubleshooting)"
    echo "gmx grompp -f nvt-equil.mdp -c $gro -o Run.tpr -p $top $index -v >& Grompp.log" > cmd.file
    echo "gmx mdrun -nt $proc -s Run.tpr " >> cmd.file
    echo grompp -p $top -c confout.gro -f nvt-run.mdp -o Run.tpr $index   "(logged to Grompp-2.log for troubleshooting)"
    echo mdrun -nt $proc -s Run.tpr                         "(logged to md.log for troubleshooting)"
    echo "gmx grompp -f nvt-run.mdp -c confout.gro -o Run.tpr -p $top $index -v >& Grompp-2.log" >> cmd.file
    echo "gmx mdrun -nt $proc -s Run.tpr " >> cmd.file
else

echo grompp -p $top -c $gro -f $mdp -o Run.tpr $index   "(logged to Grompp.log for troubleshooting)"
echo mdrun -nt $proc -s Run.tpr                         "(logged to md.log for troubleshooting)"
    echo "gmx grompp -f $mdp -c $gro -o Run.tpr -p $top $index -v >& Grompp.log" > cmd.file
    echo "gmx mdrun -nt $proc -s Run.tpr " >> cmd.file

fi    

qsub <<  eof
#$ -S /bin/bash
#$ -q "$node"
#$ -N "$name"
#$ -l h_rt=999:00:00
#$ -pe mpi $proc 
#$ -cwd
#$ -j y
#$ -o Run.log 
#$ -a 1706162359

echo "BROMACS job running on the following processors:" > $JOBNAME.out
echo "grompp -f $mdp -c $gro -o Run.tpr -p $top $index -v >& Grompp.log" >> $JOBNAME.out
echo "mdrun -nt $proc -s Run.tpr" >> $JOBNAME.out
cat \$PE_HOSTFILE >> $JOBNAME.out

echo $PWD >> $JOBNAME.out

module load gromacs
export GMXLIB=/home/scha0275/gromacs/top/

export SCR=/scr/$USER/\$JOB_ID
mkdir \$SCR
export TMPDIR=\$SCR

echo "Starting GROMACS Job!" >> $JOBNAME.out

cp \$SGE_O_WORKDIR/* \$TMPDIR/

cd \$TMPDIR 

/home/scha0275/program-workshop/python2.7/./pynscheduling.py type=gmx procs=$proc starting jid=\$JOB_ID cmd=cmd.file >> test.stuff 

rm mdout.mdp

#grompp -f nvt-run.mdp -c confout.gro -o Run.tpr -p $top $index -v >& Grompp.log

#mdrun -nt $proc -s Run.tpr $flags

sleep 10s

cp \$TMPDIR/* \$SGE_O_WORKDIR

/bin/rm -r \$SCR

echo "GROMACS Job Finished!" >> $JOBNAME.out

eof
